# Generated by Django 5.2.6 on 2025-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.PositiveIntegerField()),
                ('cases', models.PositiveIntegerField()),
                ('deaths', models.PositiveIntegerField()),
                ('vaccinations', models.PositiveIntegerField()),
                ('confirmed_deaths_per100k', models.FloatField()),
                ('excess_deaths_per100k', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'COVID Data',
                'verbose_name_plural': 'COVID Data',
                'ordering': ['-date', 'country', 'sex', 'age'],
                'indexes': [models.Index(fields=['country', 'date'], name='dashboard_c_country_1d1d7b_idx'), models.Index(fields=['date', 'sex'], name='dashboard_c_date_e53e5c_idx'), models.Index(fields=['country', 'sex'], name='dashboard_c_country_b54bba_idx')],
            },
        ),
    ]
