# Generated by Django 5.2.6 on 2025-09-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coviddata',
            unique_together={('country', 'date', 'sex', 'age')},
        ),
    ]
